name: Deploy-Azure-Storage-Account

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Azure Storage Account
        uses: stefanstranger/azure-storageaccount-action@master
        with:
          action: "createStorageAccount"
          ServiceConnection: "SERVICECONNECTION"
          StorageAccountName: "githubactiondemosa"
          ResourceGroupName: "ghactiondemo-rg"
          Location: "westeurope"
          AccountType: "Standard_LRS"
          AccessTier: "Cool"
        env: # Github Secret stored as Environment variable
          SERVICECONNECTION: ${{ secrets.AZURE_CREDENTIALS}}
