name: Remove-Azure-Storage-Account

on: [push]

jobs:
  deploy:
    name: Remove
    runs-on: ubuntu-latest
    steps:
      - name: Remove Azure Storage Account
        uses: stefanstranger/azure-storageaccount-action@master
        with:
          action: "removeStorageAccount"
          ServiceConnection: "SERVICECONNECTION"
          ResourceGroupName: "ghactiondemo-rg"
          StorageAccountName: "githubactiondemosa"
          #args: '"-action" "createStorageAccount" "-StorageAccountName" "githubactiondemosa" "-ResourceGroupName" "ghactiondemo-rg" "-Location" "westeurope" "-AccountType" "Standard_LRS" "-AccessTier" "Cool" "-ServiceConnection" "SERVICECONNECTION"'
        env: # Github Secret stored as Environment variable
          SERVICECONNECTION: ${{ secrets.AZURE_CREDENTIALS}}
